---

- name: Install PHP packages
  run_once: true
  yum: name={{ item }} state=present
  with_items:
      - php
      - php-cli
      - php-pecl-imagick
      - php-curl
      - php-gd
      - php-fpm
      - php-memcache
      - php-memcached
      - php-xdebug
      - phpunit
      - libselinux-python

- name: PHP-fpm template
  template: src=www.conf dest=/etc/php-fpm.d/{{inventory_hostname}}.conf
  notify: restart php-fpm

  
