---
- name: install webtatic repo
  run_once: true
  yum: name=https://mirror.webtatic.com/yum/el7/webtatic-release.rpm state=present

- name: Install PHP packages
  run_once: true
  yum: name={{ item }} state=present
  with_items:
      - php56w
      - php56w-cli
      - php56w-pecl-imagick
      - php56w-curl
      - php56w-gd
      - php56w-fpm
      - php56w-pecl-memcache
      - php56w-pecl-memcached
      - php56w-pecl-apcu
      - libselinux-python

- file: path=/etc/php-fpm.d/www.conf state=absent

- name: PHP-fpm template
  template: src=www.conf dest=/etc/php-fpm.d/{{inventory_hostname}}.conf
  notify: restart php-fpm

  
