---
- hosts: all
  connection: local
  sudo: yes

  roles:
    - common
#    - { role: hhvm, when: ansible_lsb.major_release | int >= 14 }
    - php-fpm
    - memcached
#    - percona
    - {role: mysql, tags: ['mysql']}
    - nginx
    - wp-cli
    - varnish
    - { role: wordpress, enviro: hhvm, tags: [ 'wordpress' ] }
