---
- hosts: all
  connection: local
  sudo: yes

  roles:
    - common
    - hhvm
    - php-fpm
    - memcached
#    - percona
#    - {role: mysql, tags: ['mysql']}
    - {role: mariadb, tags: ['mysql']}
    - nginx
    - wp-cli
    - varnish
    - { role: wordpress, enviro: hhvm, tags: [ 'wordpress' ] }
