---
- name: Add the debianized repo file
#  copy: src=debianized.repo dest=/etc/yum.repos.d/debianized.repo
  template: src=no1youknowz-hhvm-repo-epel-7.repo dest=/etc/yum.repos.d/no1youknowz-hhvm-repo-epel-7.repo

- name: Install hhvm
  yum: "name={{ item }} state=present"
  with_items:
#    - "hhvm-{{ hhvm_version }}"
    - hhvm
- name: new service config
  template: src=hhvm.service dest=/etc/systemd/system/hhvm.service

- name: change permissions
  file: path=/var/run/hhvm owner=nginx

- name: Do /etc/hhvm/server.ini
  run_once: true
  template: src=etc/hhvm/config.ini dest=/etc/hhvm/config.ini owner=root group=root mode=0644
  notify: hhvm restart

- name: Do /etc/hhvm/php.ini
  run_once: true
  template: src=etc/hhvm/php.ini dest=/etc/hhvm/php.ini owner=root group=root mode=0644
  notify: hhvm restart

